# erlang.mk Makefile for emprng

PROJECT = emprng

CT_SUITES = rand

ERLC_OPTS = -Werror +debug_info +warn_export_all +warn_export_vars \
	        +warn_shadow_vars +warn_obsolete_guard +bin_opt_info +warn_missing_spec
# Uncomment this for enabling HiPE
#ERLC_OPTS += +native "+{hipe, [o3]}"

DIALYZER_OPTS = -Wrace_conditions -Wunmatched_returns

include erlang.mk
